### ISSUE TITLE
cannot open codeinspect on ubuntu 14.04

### ISSUE THREAD

**Issue by magicislab** [secure-software-engineering/CodeInspect#102]
HI, I just tried to open the codeinspect under ubuntu 14.04,but it didn't work. The error is following: 
![screenshot from 2015-03-25 08 33 09](https://cloud.githubusercontent.com/assets/10672049/6816109/ab343bf8-d2c9-11e4-862c-23ea331d2bbd.png)

**Comment by MarcMil** [comment]
The problem is probably related due to incompatibilities with CodeInspect and the web rendering engine installed on your system.
You can try to add either
-Dorg.eclipse.swt.browser.DefaultType=webkit
or
-Dorg.eclipse.swt.browser.DefaultType=mozilla
to CodeInspect.ini in the main path of CodeInspect. With at least one of these CodeInspect will crash like you have seen it; the other one might work.
Do you have problems with running normal eclipse?

**Comment by StevenArzt** [comment]
@magicislab Does the problem still occur?

**Comment by magicislab** [comment]
The problem does not occur. Thanks a lot!






毕野



我的企业/上研院










 
 
 
------------------ Original ------------------

**Comment by magicislab** [comment]
No, it does not occur.
