### ISSUE TITLE
Compile error on twitter apk

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#82]
Hi: 

I used codeinspect to analysis twitter apk, however there are 24 compilation errors and cannot produce output.apk.

Errors are all in res folder, and are as follows:

```
Description	Resource	Path	Location	Type
Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Holo.DialogPreference.YesNoPreference'.	styles.xml	/com.twitter.android-2.apk/res/values-v21	line 45	Compilation Problem
```

```
Description	Resource	Path	Location	Type
Error: No resource found that matches the given name: attr 'android:borderRight'.	styles.xml	/com.twitter.android-2.apk/res/values-v21	line 55	Compilation Problem
```
twitter apk attached here: http://box.myqsc.com/-53922620

**Comment by flankerhqd** [comment]
![screenshot from 2015-03-11 14 04 04](https://cloud.githubusercontent.com/assets/2270027/6591237/a08a391e-c7f7-11e4-96d8-94b89ab163cf.png)

**Comment by flankerhqd** [comment]
In case the download link is not available, see https://onedrive.live.com/redir?resid=A81B51F05D7E3C2F!7550&authkey=!AHwjUUTA43UQR7o&ithint=file%2capk

**Comment by MarcMil** [comment]
These errors are generated by the Android Asset Packaging Tool (aapt), which is used to build the resource files. CodeInspect will use the aapt found in the build-tools folder of your Android SDK.

Check whether you have installed the newest Android SDK Build-tools. You can do so via the menu "Android/Show SDK window".


What I would currently do is trying to remove the affected lines/files until aapt stops complaining.

It's a bit strange. Although I have installed version 22.0.0 of the build-tools, aapt still complains about the resources in the v21 folder, even if I place
 <uses-sdk android:targetSdkVersion="21"/>
in the manifest file.

This issue might take some time to resolve as it needs further investigation and the bug is not clearly on CodeInspect's side. I am unsure whether apktool creates invalid Android XML files or aapt is unwilling to accept legit files.

**Comment by StevenArzt** [comment]
I also had a similar problem with one APK file. The solution for me was to just remove the offending attribute. Maybe something's really wrong there with apktool.

**Comment by srasthofer** [comment]
@StevenArzt: yes this would be a temporary solution, but not a long-term. Thanks for that comment

**Comment by MarcMil** [comment]
OK, I here is the solution which works for me (the same that works for the other issue as well). However, please download a new version of CodeInspect, since there was also another issue with the APK.

You have a older version of your framework files installed, which causes apktool to fail creating valid xml files.

You have to remove them, so that apktool can install a newer version of them.
Linux
remove $HOME/apktool/framework/1.apk

Windows:
remove %HOMEPATH%\apktool\framework\1.apk

and reimport the apk into Codeinspect.

**Comment by flankerhqd** [comment]
Fix confirmed
